<div class="info">
    <h2><strong>vc</strong>: Virtual Content</h2>
    <h3>What's it all about then?</h3>
    <p>
        <strong>vc</strong> is a digital art project by North East England-based British/Australian
        software engineer <a target="_blank" href="https://twitter.com/alexmoonpro">Alex Moon</a>.
    </p>
    <p>
        Combining existing AI/machine learning technologies to create explorable dream
        worlds, <strong>vc</strong> is a series of short videos which employs a poetic approach
        to the emerging form that is AI-generated visual art.
    </p>
    <p>
        Human and machine collaborate to give expression
        to the latent content of an unprecedented technological age.
    </p>
    <h3>Acknowledgements</h3>
    <p>
        This work is built on the shoulders of giants, including:
        <ul>
            <li><a target="_blank" href="https://twitter.com/advadnoun">Ryan Murdock</a></li>
            <li><a target="_blank" href="https://twitter.com/rivershavewings">Katherine Crowson</a></li>
            <li><a target="_blank" href="https://github.com/nerdyrodent">Nerdy Rodent</a></li>
            <li><a target="_blank" href="https://shihmengli.github.io/3D-Photo-Inpainting">Shih, Meng-Li and Su, Shih-Yang and Kopf, Johannes and Huang, Jia-Bin</a></li>
            <li><a target="_blank" href="https://idealo.github.io/image-super-resolution">Francesco Cardinale et al.</a></li>
        </ul>
    </p>
    <!-- h3>Buy the artwork</h3>
    <p>
        Individual videos are available to view on
        <a target="_blank" href="https://opensea.io/collection/vc-ajmoon-uk">OpenSea</a>.
    </p -->
</div>
