<div class="info-container">
    <div class="info">
        <div class="text">
            <h2><strong>vc</strong>: Virtual Content</h2>
            <p>
                <strong>vc</strong> is a digital art project by North East England-based British/Australian
                software engineer <a target="_blank" href="https://twitter.com/alexmoonpro">Alex Moon</a>.
            </p>
            <p>
                Combining existing AI/machine learning technologies to create explorable dream worlds,
                <strong>vc</strong> is a series of short videos which bring a poetic touch to the
                emerging form. Each piece is crafted with care, and the results are like nothing
                you've seen.
            </p>
            <div class="actions">
                <button class="close">Show me</button>
            </div>
            <h3>Acknowledgements</h3>
            <p>
                These works are built on the following AI stack. We would like to thank the
                authors for making their code available.
            </p>
            <ul>
                <li>
                    <a target="_blank" href="https://github.com/CompVis/taming-transformers">
                        <strong>VQGAN</strong>
                        <span>Patrick Esser, Robin Rombach, Björn Ommer</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://github.com/openai/CLIP">
                        <strong>CLIP</strong>
                        <span>Alec Radford, Jong Wook Kim, Chris Hallacy, Aditya Ramesh, Gabriel Goh, Sandhini Agarwal, Girish Sastry, Amanda Askell, Pamela Mishkin, Jack Clark, Gretchen Krueger, Ilya Sutskever</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://github.com/isl-org/MiDaS">
                        <strong>MiDaS</strong>
                        <span>René Ranftl, Katrin Lasinger, David Hafner, Konrad Schindler, Vladlen Koltun</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://shihmengli.github.io/3D-Photo-Inpainting">
                        <strong>3D Photo Inpainting</strong>
                        <span>Meng-Li Shih, Shih-Yang Su, Johannes Kopf, Jia-Bin Huang</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://github.com/xinntao/Real-ESRGAN">
                        <strong>ESRGAN</strong>
                        <span>Xintao Wang, Liangbin Xie, Chao Dong, Ying Shan</span>
                    </a>
                </li>
            </ul>
            <p>
                Works created prior to Friday 8 October 2021 used the following in place
                of <strong>MiDaS</strong> and <strong>ESRGAN</strong>.
            </p>
            <ul>
                <li>
                    <a target="_blank" href="https://github.com/compphoto/BoostingMonocularDepth">
                        <strong>BoostingMonocularDepth</strong>
                        <span>S. Mahdi H. Miangoleh, Sebastian Dille, Long Mai, Sylvain Paris, and Yağız Aksoy</span>
                    </a>
                </li>
                <li>
                    <a target="_blank" href="https://idealo.github.io/image-super-resolution">
                        <strong>ISR</strong>
                        <span>Francesco Cardinale et al.</span>
                    </a>
                </li>
            </ul>
            <div class="actions">
                <button class="close">Show me</button>
            </div>
        </div>
    </div>
</div>
