version: '3.7'
services:
  vc:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vc
    expose:
      - 5000
      - 5001
    ports:
      - mode: host
        protocol: tcp
        published: 5000
        target: 5000
      - mode: host
        protocol: tcp
        published: 5001
        target: 5001
    volumes:
      - .:/app
      - .bashrc:/root/.bashrc
    # command: sleep 999999999
    command: ./local-wrapper.sh

