version: '3.7'
services:
  flask:
    build:
      context: ./
      dockerfile: docker/flask/Dockerfile
    image: vc.ajmoon.com/flask
    volumes:
      - .:/opt/vc
      - .bashrc:/root/.bashrc
    environment:
      SERVICE: flask
    links:
      - pgsql
    extra_hosts:
      - "laravel.local:192.168.99.198"
    command: ./docker.flask.sh

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: vc.ajmoon.com/nginx
    links:
      - flask
    volumes:
      - .:/opt/vc
      - ./log/nginx/:/var/log/nginx
      - ./docker/nginx/conf/flask.conf:/etc/nginx/nginx.conf
    ports:
      - "10001:80"

  pgsql:
    image: postgis/postgis:9.5-2.5-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgsql:/var/lib/postgresql/data
    ports:
      - "15433:5432"

#  worker:
#    image: vc.ajmoon.com/flask
#    volumes:
#      - .:/opt/vc
#      - .bashrc:/root/.bashrc
#    links:
#      - pgsql
#      - redis
#    depends_on:
#      - pgsql
#    environment:
#      SERVICE: worker
#    command: sleep 999999999
    # command: ./docker.worker.sh

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    image: vc.ajmoon.com/redis
    ports:
      - "16380:6379"
