version: '3'

tasks:
  start: scripts/aws.start.sh
  stop: scripts/aws.stop.sh
  sh: scripts/sh.sh
  build: scripts/build.sh
  run: scripts/run.sh
  db: scripts/db.sh
  dump: scripts/dump.sh
  migrate: scripts/migrate.sh
  restore: scripts/restore.sh

  webpack: npx webpack --node-env=local

  serve:
    cmds:
      - task: webpack
      - npx webpack serve --node-env=local

#  deploy_backend: scripts/backend.sh
#
#  deploy_frontend: scripts/frontend.sh
#
#  deploy_private:
#    deps: [deploy_backend, deploy_frontend]
#
#  deploy.public: scripts/public.sh
#
#  deploy:
#    deps: [deploy_private, deploy_public]

  deploy:
    env:
      app: vc
    cmds:
      - |
        ssh -t ajmoon "
          if [[ ! -d '/opt/$app' ]]; then
            mkdir /opt/$app
            cd /opt/$app
            git clone https://github.com/alex-moon/$app .
          fi
          cd /opt/$app
          git reset --hard HEAD
          git pull origin \$(git rev-parse --abbrev-ref HEAD)
          docker compose build
          docker stack deploy -c docker-compose.yml $app
          docker run --rm -i \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -u root ubirak/docker-php:latest \
            stack:converge $app
          docker system prune -f
          scripts/frontend.sh
          # scripts/backend.sh
        "
