"""empty message

Revision ID: 1f1183df052e
Revises: d28e58480a67
Create Date: 2021-09-24 19:11:18.522707

"""
import os

import dotenv
import sqlalchemy as sa
from sqlalchemy import orm
from alembic import op

from vc.model.user import User

# revision identifiers, used by Alembic.
revision = '1f1183df052e'
down_revision = 'd28e58480a67'
branch_labels = None
depends_on = None


def upgrade():
    dotenv.load_dotenv()
    connection = op.get_bind()
    session = orm.Session(bind=connection)
    user = User(
        email=os.environ.get('APP_ADMIN_EMAIL'),
        token=os.environ.get('APP_ADMIN_TOKEN')
    )
    session.add(user)
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('user_id', sa.Integer(), nullable=True))

    # set default
    table = sa.table(
        'generation_request',
        sa.column('id', sa.Integer()),
        sa.column('user_id', sa.Integer())
    )
    connection.execute(table.update().values(user_id=user.id))
    op.alter_column('generation_request', 'user_id', nullable=False)

    op.add_column('generation_request', sa.Column('cancelled', sa.DateTime(), nullable=True))
    op.add_column('generation_request', sa.Column('interim_watermarked', sa.String(), nullable=True))
    op.create_foreign_key(None, 'generation_request', 'user', ['user_id'], ['id'])
    op.add_column('generation_result', sa.Column('url_watermarked', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_result', 'url_watermarked')
    op.drop_constraint(None, 'generation_request', type_='foreignkey')
    op.drop_column('generation_request', 'interim_watermarked')
    op.drop_column('generation_request', 'cancelled')
    op.drop_column('generation_request', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
