"""empty message

Revision ID: 25ee53e98547
Revises: a684c982c890
Create Date: 2021-12-03 21:54:48.404356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ee53e98547'
down_revision = 'a684c982c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True, default='AJ Moon'))
    op.add_column('user', sa.Column('tier', sa.Integer(), nullable=False, default=3))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
