"""empty message

Revision ID: 25ee53e98547
Revises: a684c982c890
Create Date: 2021-12-03 21:54:48.404356

"""

import dotenv
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

# revision identifiers, used by Alembic.
revision = '25ee53e98547'
down_revision = 'a684c982c890'
branch_labels = None
depends_on = None


def upgrade():
    dotenv.load_dotenv()
    connection = op.get_bind()
    session = orm.Session(bind=connection)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('tier', sa.Integer(), nullable=True))

    # set default because alembic is garbage
    table = sa.table(
        'user',
        sa.column('id', sa.Integer()),
        sa.column('tier', sa.Integer()),
        sa.column('name', sa.String()),
        sa.column('token', sa.String())
    )
    connection.execute(table.update().values(
        tier=3,
        name='AJ Moon',
        token='$2b$12$2o3CS88trnMm9jO7YNRkU.FK8K6BUlFH0S3Eb0O.OB8CVMNRwQm7i'
    ))
    op.alter_column('user', 'tier', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tier')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
