"""empty message

Revision ID: 93a7808e92a0
Revises: e697d411bad2
Create Date: 2021-10-16 17:31:57.959707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a7808e92a0'
down_revision = 'e697d411bad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_request', 'hash')
    # ### end Alembic commands ###
