"""empty message

Revision ID: d28e58480a67
Revises: 
Create Date: 2021-09-19 14:16:17.170841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e58480a67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('deleted', sa.DateTime(), nullable=True))
    op.add_column('generation_result', sa.Column('deleted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_result', 'deleted')
    op.drop_column('generation_request', 'deleted')
    # ### end Alembic commands ###
