"""empty message

Revision ID: e697d411bad2
Revises: e73dfbb992d5
Create Date: 2021-10-15 23:14:06.257995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e697d411bad2'
down_revision = 'e73dfbb992d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_request', sa.Column('retried', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generation_request', 'retried')
    # ### end Alembic commands ###
